extends: ./node_modules/tn-conventions/scss/.stylelintrc.yml
rules:
  # SCSS naming patterns, just like our CSS conventions above.
  # (note for $-vars we use a leading underscore for "private" variables)
  scss/dollar-variable-pattern:
    - ^_?tn-.+
    -
      ignore: local
  scss/at-function-pattern: ^tn-.+
  scss/at-mixin-pattern: ^tn-.+
